#!/usr/bin/env npx tsx

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { mergeTagIds, validateTagSelection } from '../../lib/tags';
import {
  classifyCatalog,
  type AppleArtistLookup,
  type CatalogSong,
  type TagAssignment,
} from './classify';

interface StoredSong {
  id: string;
  workId?: string;
  title: string;
  originalArtist: string;
  tags: string[];
  performances: Array<{ note?: string }>;
}

interface Registry {
  streamers: Array<{ slug: string; displayName: string }>;
}

interface AppleMetadata {
  fetchedAt: string;
  lookups: AppleArtistLookup[];
}

interface CatalogRecord {
  id: string;
  title: string;
  originalArtist: string;
  tags: string[];
  evidence: Record<string, string>;
}

interface SongCatalogRecord extends CatalogRecord {
  workId: string;
  streamer: string;
}

interface TagCatalog {
  schemaVersion: 1;
  generatedAt: string;
  methodology: string;
  sources: string[];
  summary: {
    totalWorks: number;
    totalSongs: number;
    taggedWorks: number;
    taggedSongs: number;
    effectiveTaggedSongs: number;
    countsByTag: Record<string, number>;
  };
  works: CatalogRecord[];
  songs: SongCatalogRecord[];
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const DATA_DIR = path.resolve(ROOT, 'data');
const APPLE_METADATA = path.resolve(__dirname, 'apple-artist-metadata.json');
const OUTPUT = path.resolve(DATA_DIR, 'tag-catalog.json');
const MIGRATION_OUTPUT = path.resolve(ROOT, 'admin/migrations/0007_seed_initial_tags.sql');
const SEED_TABLE = '_tag_catalog_seed_0007';

function readAppleMetadata(): AppleMetadata {
  if (!fs.existsSync(APPLE_METADATA)) return { fetchedAt: new Date(0).toISOString(), lookups: [] };
  return JSON.parse(fs.readFileSync(APPLE_METADATA, 'utf8')) as AppleMetadata;
}

function readPreviousCatalog(): TagCatalog | null {
  if (!fs.existsSync(OUTPUT)) return null;
  return JSON.parse(fs.readFileSync(OUTPUT, 'utf8')) as TagCatalog;
}

function assignmentTags(assignments: TagAssignment[] | undefined): string[] {
  return assignments?.map((assignment) => assignment.tag) ?? [];
}

function evidenceByTag(assignments: TagAssignment[]): Record<string, string> {
  return Object.fromEntries(assignments.map(({ tag, evidence }) => [tag, evidence]));
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function renderSeedInserts(scope: 'work' | 'song', records: CatalogRecord[]): string {
  const statements: string[] = [];
  const batchSize = 200;
  for (let offset = 0; offset < records.length; offset += batchSize) {
    const values = records.slice(offset, offset + batchSize).map((record) =>
      `  (${sqlString(scope)}, ${sqlString(record.id)}, ${sqlString(JSON.stringify(record.tags))})`
    );
    statements.push(`INSERT INTO ${SEED_TABLE} (scope, id, tags) VALUES\n${values.join(',\n')};`);
  }
  return statements.join('\n\n');
}

function renderUpdate(table: 'works' | 'songs', scope: 'work' | 'song'): string {
  return `UPDATE ${table}\nSET tags = (\n  SELECT json_group_array(value)\n  FROM (\n    SELECT DISTINCT value\n    FROM (\n      SELECT value FROM json_each(\n        CASE WHEN json_valid(${table}.tags) THEN ${table}.tags ELSE '[]' END\n      )\n      UNION ALL\n      SELECT value FROM json_each((\n        SELECT seed.tags\n        FROM ${SEED_TABLE} AS seed\n        WHERE seed.scope = ${sqlString(scope)} AND seed.id = ${table}.id\n      ))\n    )\n    ORDER BY value\n  )\n),\nupdated_at = datetime('now')\nWHERE EXISTS (\n  SELECT 1 FROM ${SEED_TABLE} AS seed\n  WHERE seed.scope = ${sqlString(scope)} AND seed.id = ${table}.id\n);`;
}

function renderMigration(works: CatalogRecord[], songs: SongCatalogRecord[]): string {
  return `-- Generated by npm run tags:build. Do not edit by hand.\n--\n-- Initial, conservative tag backfill. Existing D1 tags are preserved and the\n-- migration is idempotent, so it is safe to retry after an interrupted rollout.\n\nDROP TABLE IF EXISTS ${SEED_TABLE};\nCREATE TABLE ${SEED_TABLE} (\n  scope TEXT NOT NULL CHECK(scope IN ('work', 'song')),\n  id TEXT NOT NULL,\n  tags TEXT NOT NULL CHECK(json_valid(tags)),\n  PRIMARY KEY (scope, id)\n);\n\n${renderSeedInserts('work', works)}\n\n${renderSeedInserts('song', songs)}\n\n${renderUpdate('works', 'work')}\n\n${renderUpdate('songs', 'song')}\n\nDROP TABLE ${SEED_TABLE};\n`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const registry = JSON.parse(fs.readFileSync(path.resolve(DATA_DIR, 'registry.json'), 'utf8')) as Registry;
  const displayNamesBySlug = new Map(registry.streamers.map((streamer) => [streamer.slug, streamer.displayName]));
  const apple = readAppleMetadata();
  const previous = readPreviousCatalog();
  const previousTagsByWork = new Map(previous?.works.map((work) => [work.id, work.tags]) ?? []);
  const previousTagsBySong = new Map(previous?.songs.map((song) => [song.id, song.tags]) ?? []);
  const storedBySlug = new Map<string, StoredSong[]>();
  const songs: CatalogSong[] = [];

  for (const entry of fs.readdirSync(DATA_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const songsPath = path.resolve(DATA_DIR, entry.name, 'songs.json');
    if (!fs.existsSync(songsPath)) continue;
    const stored = JSON.parse(fs.readFileSync(songsPath, 'utf8')) as StoredSong[];
    storedBySlug.set(entry.name, stored);
    for (const song of stored) {
      if (!song.workId) throw new Error(`${entry.name}/${song.id} has no workId; tag catalog requires stable work identities`);
      songs.push({
        slug: entry.name,
        id: song.id,
        workId: song.workId,
        title: song.title,
        originalArtist: song.originalArtist,
        performances: song.performances,
      });
    }
  }

  const songIds = new Set<string>();
  for (const song of songs) {
    if (songIds.has(song.id)) throw new Error(`duplicate song ID across streamer data: ${song.id}`);
    songIds.add(song.id);
  }

  const classified = classifyCatalog(songs, apple.lookups, displayNamesBySlug);
  const identityByWork = new Map<string, CatalogSong>();
  for (const song of [...songs].sort((left, right) => left.id.localeCompare(right.id))) {
    if (!identityByWork.has(song.workId)) identityByWork.set(song.workId, song);
  }

  const works = [...classified.workAssignments]
    .map(([id, assignments]): CatalogRecord => {
      const identity = identityByWork.get(id)!;
      return {
        id,
        title: identity.title,
        originalArtist: identity.originalArtist,
        tags: assignmentTags(assignments),
        evidence: evidenceByTag(assignments),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));

  const songById = new Map(songs.map((song) => [song.id, song]));
  const catalogSongs = [...classified.songAssignments]
    .map(([id, assignments]): SongCatalogRecord => {
      const identity = songById.get(id)!;
      return {
        id,
        workId: identity.workId,
        streamer: identity.slug,
        title: identity.title,
        originalArtist: identity.originalArtist,
        tags: assignmentTags(assignments),
        evidence: evidenceByTag(assignments),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));

  for (const record of [...works, ...catalogSongs]) {
    const validation = validateTagSelection(record.tags);
    if (!validation.ok) throw new Error(`${record.id}: ${validation.error}`);
  }

  const effectiveTagsBySong = new Map<string, string[]>();
  for (const song of songs) {
    effectiveTagsBySong.set(song.id, mergeTagIds(
      assignmentTags(classified.workAssignments.get(song.workId)),
      assignmentTags(classified.songAssignments.get(song.id)),
    ));
  }
  const countsByTag = new Map<string, number>();
  for (const tags of effectiveTagsBySong.values()) {
    for (const tag of tags) countsByTag.set(tag, (countsByTag.get(tag) ?? 0) + 1);
  }

  const catalog: TagCatalog = {
    schemaVersion: 1,
    generatedAt: apple.fetchedAt,
    methodology: 'Conservative high-confidence rules: explicit annotations and writing systems, cross-song artist profiles, curated frequent-artist review, and dominant Apple catalog genres. Ambiguous fields remain untagged.',
    sources: [
      'Repository data/*/songs.json and data/registry.json',
      'Apple iTunes Search API artist metadata snapshot in tools/tag-catalog/apple-artist-metadata.json',
    ],
    summary: {
      totalWorks: identityByWork.size,
      totalSongs: songs.length,
      taggedWorks: works.length,
      taggedSongs: catalogSongs.length,
      effectiveTaggedSongs: [...effectiveTagsBySong.values()].filter((tags) => tags.length > 0).length,
      countsByTag: Object.fromEntries([...countsByTag].sort(([left], [right]) => left.localeCompare(right))),
    },
    works,
    songs: catalogSongs,
  };

  const expectedCatalog = `${JSON.stringify(catalog, null, 2)}\n`;
  const expectedMigration = renderMigration(works, catalogSongs);
  let stale = !fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, 'utf8') !== expectedCatalog
    || !fs.existsSync(MIGRATION_OUTPUT) || fs.readFileSync(MIGRATION_OUTPUT, 'utf8') !== expectedMigration;

  for (const [slug, storedSongs] of storedBySlug) {
    const updated = storedSongs.map((song) => {
      const oldManagedTags = mergeTagIds(
        previousTagsByWork.get(song.workId ?? '') ?? [],
        previousTagsBySong.get(song.id) ?? [],
      );
      const preservedTags = song.tags.filter((tag) => !oldManagedTags.includes(tag));
      const effectiveTags = mergeTagIds(preservedTags, effectiveTagsBySong.get(song.id) ?? []);
      return { ...song, tags: effectiveTags };
    });
    const expected = `${JSON.stringify(updated, null, 2)}\n`;
    const songsPath = path.resolve(DATA_DIR, slug, 'songs.json');
    if (fs.readFileSync(songsPath, 'utf8') !== expected) stale = true;
    if (!check) fs.writeFileSync(songsPath, expected);
  }

  if (check) {
    if (stale) throw new Error('tag catalog or generated songs.json files are stale; run npm run tags:build');
  } else {
    fs.writeFileSync(OUTPUT, expectedCatalog);
    fs.writeFileSync(MIGRATION_OUTPUT, expectedMigration);
  }

  console.log(JSON.stringify(catalog.summary, null, 2));
}

main();
