#!/usr/bin/env npx tsx

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  mergeTagIds,
  validateTagSelectionForScope,
} from '../../lib/tags';
import type {
  AppleArtistLookup,
  CatalogSong,
  TagAssignment,
} from './classify';

interface StoredPerformance {
  id: string;
  note?: string;
}

interface StoredSong {
  id: string;
  workId?: string;
  title: string;
  originalArtist: string;
  performances: StoredPerformance[];
}

interface Registry {
  streamers: Array<{ slug: string; displayName: string }>;
}

interface AppleMetadata {
  fetchedAt: string;
  lookups: AppleArtistLookup[];
}

export interface CatalogRecord {
  id: string;
  title: string;
  originalArtist: string;
  tags: string[];
  evidence: Record<string, string>;
}

export interface PerformanceCatalogRecord extends CatalogRecord {
  songId: string;
  workId: string;
  streamer: string;
}

export interface TagCatalog {
  schemaVersion: 2;
  generatedAt: string;
  methodology: string;
  sources: string[];
  summary: {
    totalWorks: number;
    totalSongs: number;
    totalPerformances: number;
    taggedWorks: number;
    taggedSongs: number;
    taggedPerformances: number;
    effectiveTaggedSongs: number;
    countsByTag: Record<string, number>;
  };
  works: CatalogRecord[];
  performances: PerformanceCatalogRecord[];
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const DATA_DIR = path.resolve(ROOT, 'data');
const APPLE_METADATA = path.resolve(__dirname, 'apple-artist-metadata.json');
const OUTPUT = path.resolve(DATA_DIR, 'tag-catalog.json');
const MIGRATION_OUTPUT = path.resolve(ROOT, 'admin/migrations/0008_seed_initial_tags.sql');
const SEED_TABLE = '_tag_catalog_seed_0008';

function readAppleMetadata(): AppleMetadata {
  if (!fs.existsSync(APPLE_METADATA)) return { fetchedAt: new Date(0).toISOString(), lookups: [] };
  return JSON.parse(fs.readFileSync(APPLE_METADATA, 'utf8')) as AppleMetadata;
}

function assignmentTags(assignments: TagAssignment[] | undefined): string[] {
  return assignments?.map((assignment) => assignment.tag) ?? [];
}

function evidenceByTag(assignments: TagAssignment[]): Record<string, string> {
  return Object.fromEntries(assignments.map(({ tag, evidence }) => [tag, evidence]));
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function renderSeedInserts(scope: 'work' | 'performance', records: CatalogRecord[]): string {
  const statements: string[] = [];
  const batchSize = 200;
  for (let offset = 0; offset < records.length; offset += batchSize) {
    const values = records.slice(offset, offset + batchSize).map((record) =>
      `  (${sqlString(scope)}, ${sqlString(record.id)}, ${sqlString(JSON.stringify(record.tags))})`
    );
    statements.push(`INSERT INTO ${SEED_TABLE} (scope, id, tags) VALUES\n${values.join(',\n')};`);
  }
  return statements.join('\n\n');
}

function renderUpdate(table: 'works' | 'performances', scope: 'work' | 'performance'): string {
  return `UPDATE ${table}\nSET tags = (\n  SELECT json_group_array(value)\n  FROM (\n    SELECT DISTINCT value\n    FROM (\n      SELECT value FROM json_each(\n        CASE WHEN json_valid(${table}.tags) THEN ${table}.tags ELSE '[]' END\n      )\n      UNION ALL\n      SELECT value FROM json_each((\n        SELECT seed.tags\n        FROM ${SEED_TABLE} AS seed\n        WHERE seed.scope = ${sqlString(scope)} AND seed.id = ${table}.id\n      ))\n    )\n    ORDER BY value\n  )\n),\nupdated_at = datetime('now')\nWHERE EXISTS (\n  SELECT 1 FROM ${SEED_TABLE} AS seed\n  WHERE seed.scope = ${sqlString(scope)} AND seed.id = ${table}.id\n);`;
}

export function renderMigration(works: CatalogRecord[], performances: PerformanceCatalogRecord[]): string {
  return `-- Generated by npm run tags:seed:build. Do not edit by hand.\n--\n-- Initial, conservative tag backfill. Existing D1 tags are preserved and the\n-- migration is idempotent, so it is safe to retry after an interrupted rollout.\n-- Do not reapply it after curator ownership begins; doing so would restore tags\n-- that a curator intentionally removed.\n\nDROP TABLE IF EXISTS ${SEED_TABLE};\nCREATE TABLE ${SEED_TABLE} (\n  scope TEXT NOT NULL CHECK(scope IN ('work', 'performance')),\n  id TEXT NOT NULL,\n  tags TEXT NOT NULL CHECK(json_valid(tags)),\n  PRIMARY KEY (scope, id)\n);\n\n${renderSeedInserts('work', works)}\n\n${renderSeedInserts('performance', performances)}\n\n${renderUpdate('works', 'work')}\n\n${renderUpdate('performances', 'performance')}\n\nDROP TABLE ${SEED_TABLE};\n`;
}

async function buildSeedCatalog(): Promise<TagCatalog> {
  const { classifyCatalog } = await import('./classify');
  const registry = JSON.parse(fs.readFileSync(path.resolve(DATA_DIR, 'registry.json'), 'utf8')) as Registry;
  const displayNamesBySlug = new Map(registry.streamers.map((streamer) => [streamer.slug, streamer.displayName]));
  const apple = readAppleMetadata();
  const songs: CatalogSong[] = [];

  for (const entry of fs.readdirSync(DATA_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const songsPath = path.resolve(DATA_DIR, entry.name, 'songs.json');
    if (!fs.existsSync(songsPath)) continue;
    const stored = JSON.parse(fs.readFileSync(songsPath, 'utf8')) as StoredSong[];
    for (const song of stored) {
      if (!song.workId) throw new Error(`${entry.name}/${song.id} has no workId; tag catalog requires stable work identities`);
      songs.push({
        slug: entry.name,
        id: song.id,
        workId: song.workId,
        title: song.title,
        originalArtist: song.originalArtist,
        performances: song.performances,
      });
    }
  }

  const songIds = new Set<string>();
  const performanceIds = new Set<string>();
  for (const song of songs) {
    if (songIds.has(song.id)) throw new Error(`duplicate song ID across streamer data: ${song.id}`);
    songIds.add(song.id);
    for (const performance of song.performances) {
      if (performanceIds.has(performance.id)) {
        throw new Error(`duplicate performance ID across streamer data: ${performance.id}`);
      }
      performanceIds.add(performance.id);
    }
  }

  const classified = classifyCatalog(songs, apple.lookups, displayNamesBySlug);
  const identityByWork = new Map<string, CatalogSong>();
  for (const song of [...songs].sort((left, right) => left.id.localeCompare(right.id))) {
    if (!identityByWork.has(song.workId)) identityByWork.set(song.workId, song);
  }

  const works = [...classified.workAssignments]
    .map(([id, assignments]): CatalogRecord => {
      const identity = identityByWork.get(id)!;
      return {
        id,
        title: identity.title,
        originalArtist: identity.originalArtist,
        tags: assignmentTags(assignments),
        evidence: evidenceByTag(assignments),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));

  const identityByPerformance = new Map(
    songs.flatMap((song) => song.performances.map((performance) => [
      performance.id,
      { song, performance },
    ] as const)),
  );
  const catalogPerformances = [...classified.performanceAssignments]
    .map(([id, assignments]): PerformanceCatalogRecord => {
      const identity = identityByPerformance.get(id)!;
      return {
        id,
        songId: identity.song.id,
        workId: identity.song.workId,
        streamer: identity.song.slug,
        title: identity.song.title,
        originalArtist: identity.song.originalArtist,
        tags: assignmentTags(assignments),
        evidence: evidenceByTag(assignments),
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));

  for (const record of works) {
    const validation = validateTagSelectionForScope(record.tags, 'work');
    if (!validation.ok) throw new Error(`${record.id}: ${validation.error}`);
  }
  for (const record of catalogPerformances) {
    const validation = validateTagSelectionForScope(record.tags, 'performance');
    if (!validation.ok) throw new Error(`${record.id}: ${validation.error}`);
  }

  const effectiveTagsBySong = new Map<string, string[]>();
  for (const song of songs) {
    effectiveTagsBySong.set(song.id, mergeTagIds(
      assignmentTags(classified.workAssignments.get(song.workId)),
      song.performances.flatMap((performance) => (
        assignmentTags(classified.performanceAssignments.get(performance.id))
      )),
    ));
  }
  const countsByTag = new Map<string, number>();
  for (const tags of effectiveTagsBySong.values()) {
    for (const tag of tags) countsByTag.set(tag, (countsByTag.get(tag) ?? 0) + 1);
  }

  return {
    schemaVersion: 2,
    generatedAt: apple.fetchedAt,
    methodology: 'Conservative high-confidence rules: explicit annotations and writing systems, cross-song artist profiles, curated frequent-artist review, and identity-verified dominant Apple catalog genres. Ambiguous fields remain untagged.',
    sources: [
      'Repository data/*/songs.json and data/registry.json',
      'Apple iTunes Search API artist metadata snapshot in tools/tag-catalog/apple-artist-metadata.json',
    ],
    summary: {
      totalWorks: identityByWork.size,
      totalSongs: songs.length,
      totalPerformances: performanceIds.size,
      taggedWorks: works.length,
      taggedSongs: new Set(catalogPerformances.map((performance) => performance.songId)).size,
      taggedPerformances: catalogPerformances.length,
      effectiveTaggedSongs: [...effectiveTagsBySong.values()].filter((tags) => tags.length > 0).length,
      countsByTag: Object.fromEntries([...countsByTag].sort(([left], [right]) => left.localeCompare(right))),
    },
    works,
    performances: catalogPerformances,
  };
}

function assertCatalogRecords(
  records: CatalogRecord[],
  scope: 'work' | 'performance',
): void {
  const ids = new Set<string>();
  for (const record of records) {
    if (!record.id || ids.has(record.id)) {
      throw new Error(`duplicate or empty ${scope} catalog ID: ${record.id}`);
    }
    ids.add(record.id);

    if (!Array.isArray(record.tags) || record.tags.length === 0) {
      throw new Error(`${record.id}: seed catalog records must have at least one tag`);
    }
    const validation = validateTagSelectionForScope(record.tags, scope);
    if (!validation.ok) throw new Error(`${record.id}: ${validation.error}`);
    if (new Set(record.tags).size !== record.tags.length) {
      throw new Error(`${record.id}: seed catalog tags must be unique`);
    }

    const evidenceTags = Object.keys(record.evidence ?? {}).sort();
    const assignedTags = [...record.tags].sort();
    if (JSON.stringify(evidenceTags) !== JSON.stringify(assignedTags)) {
      throw new Error(`${record.id}: evidence keys must exactly match assigned tags`);
    }
    for (const evidence of Object.values(record.evidence)) {
      if (!evidence.trim()) throw new Error(`${record.id}: tag evidence must not be empty`);
    }
  }
}

function assertSummary(catalog: TagCatalog): void {
  const { summary } = catalog;
  if (!summary || summary.taggedWorks !== catalog.works.length) {
    throw new Error('seed catalog summary taggedWorks does not match its work records');
  }
  if (summary.taggedPerformances !== catalog.performances.length) {
    throw new Error('seed catalog summary taggedPerformances does not match its performance records');
  }
  const taggedSongs = new Set(catalog.performances.map((performance) => performance.songId)).size;
  if (summary.taggedSongs !== taggedSongs) {
    throw new Error('seed catalog summary taggedSongs does not match its performance records');
  }
  if (summary.totalWorks < summary.taggedWorks
    || summary.totalSongs < summary.taggedSongs
    || summary.totalPerformances < summary.taggedPerformances
    || summary.totalSongs < summary.effectiveTaggedSongs) {
    throw new Error('seed catalog summary totals are inconsistent');
  }
}

export function verifySeedArtifacts(catalog: TagCatalog, migration: string): void {
  if (!catalog || catalog.schemaVersion !== 2) {
    throw new Error('seed catalog must use schemaVersion 2');
  }
  if (!Array.isArray(catalog.works) || !Array.isArray(catalog.performances)) {
    throw new Error('seed catalog must contain work and performance records');
  }

  assertCatalogRecords(catalog.works, 'work');
  assertCatalogRecords(catalog.performances, 'performance');
  assertSummary(catalog);

  const expectedMigration = renderMigration(catalog.works, catalog.performances);
  if (migration !== expectedMigration) {
    throw new Error('initial tag migration is stale; it must be generated from the frozen seed catalog');
  }
}

export function checkSeedArtifacts(
  catalogPath: string = OUTPUT,
  migrationPath: string = MIGRATION_OUTPUT,
): TagCatalog {
  if (!fs.existsSync(catalogPath)) throw new Error(`seed catalog does not exist: ${catalogPath}`);
  if (!fs.existsSync(migrationPath)) throw new Error(`initial tag migration does not exist: ${migrationPath}`);

  const catalogText = fs.readFileSync(catalogPath, 'utf8');
  const catalog = JSON.parse(catalogText) as TagCatalog;
  const canonicalCatalog = `${JSON.stringify(catalog, null, 2)}\n`;
  if (catalogText !== canonicalCatalog) {
    throw new Error('seed catalog JSON is not in canonical generated form');
  }
  verifySeedArtifacts(catalog, fs.readFileSync(migrationPath, 'utf8'));
  return catalog;
}

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  const check = args.has('--check');
  const buildSeed = args.has('--build-seed');
  if (args.size !== 1 || check === buildSeed) {
    throw new Error('usage: build.ts --check | --build-seed');
  }

  if (check) {
    const catalog = checkSeedArtifacts();
    console.log(JSON.stringify(catalog.summary, null, 2));
  } else {
    const catalog = await buildSeedCatalog();
    const expectedCatalog = `${JSON.stringify(catalog, null, 2)}\n`;
    const expectedMigration = renderMigration(catalog.works, catalog.performances);
    verifySeedArtifacts(catalog, expectedMigration);
    fs.writeFileSync(OUTPUT, expectedCatalog);
    fs.writeFileSync(MIGRATION_OUTPUT, expectedMigration);
    console.log(JSON.stringify(catalog.summary, null, 2));
  }
}

const isMain = process.argv[1] !== undefined
  && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  void main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
