// Generates the design-sync bundle entry (+ a runtime shim) from
// cfg.componentSrcMap. Output is gitignored (.cache/); this generator + the
// config are the committed source of truth, so re-syncs regenerate both.
// Wired into cfg.buildCmd — runs before the converter on every build/re-sync.
//
// Two problems it solves:
//  1. Default exports. Every prism.oshi.tw component is a DEFAULT export; the
//     converter's stock synth-entry uses `export * from`, which drops defaults.
//     We emit explicit `export { default as <Name> }` so all reach the global.
//  2. Node globals. The components import next/link, next/navigation, etc.,
//     whose client runtime reads process.env.__NEXT_* / NEXT_RUNTIME. In the
//     browser `process` is undefined → "process is not defined" at eval time.
//     A shim module imported FIRST defines a minimal process so those reads
//     yield undefined (Next falls back to defaults). It must be a separate
//     imported module: ESM evaluates imported modules before the entry's own
//     top-level statements, so an inline assignment would run too late.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative } from 'node:path';

const CONFIG = '.design-sync/config.json';
const CACHE = '.design-sync/.cache';
const ENTRY = `${CACHE}/ds-entry.mjs`;
const SHIM = `${CACHE}/_ds-shim.mjs`;

const cfg = JSON.parse(readFileSync(CONFIG, 'utf8'));
const map = cfg.componentSrcMap ?? {};

mkdirSync(CACHE, { recursive: true });

// Runtime shim — evaluated first (see header note #2).
writeFileSync(
  SHIM,
  `// Auto-generated by .design-sync/gen-entry.mjs — do not edit.\n` +
    `// Minimal Node globals for browser-bundled Next.js runtime code.\n` +
    `globalThis.process ||= { env: {}, browser: true, platform: 'browser' };\n`,
);

const exportLines = Object.entries(map)
  .filter(([, p]) => typeof p === 'string')
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, p]) => {
    let spec = relative(dirname(ENTRY), p).replace(/\.(tsx|jsx|ts|js|mjs|cjs)$/, '');
    if (!spec.startsWith('.')) spec = './' + spec;
    return `export { default as ${name} } from ${JSON.stringify(spec)};`;
  });

writeFileSync(ENTRY, `import './_ds-shim.mjs';\n` + exportLines.join('\n') + '\n');
console.error(`gen-entry: wrote shim + ${exportLines.length} exports → ${ENTRY}`);
