#!/usr/bin/env npx tsx
/**
 * sync-registry: Dump approved Nova DB submissions → data/registry.json + lib/streamer-slugs.ts
 *
 * Usage: npx tsx tools/sync-registry/sync.ts
 *
 * Follows the same "source → static JSON" pattern as prismlens.
 * Runs wrangler from tools/nova/ where wrangler.toml binds oshi-prism-nova.
 */

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// --- Paths ---

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '../..');
const NOVA_DIR = path.resolve(ROOT, 'tools/nova');
const REGISTRY_PATH = path.resolve(ROOT, 'data/registry.json');
const SLUGS_PATH = path.resolve(ROOT, 'lib/streamer-slugs.ts');

// --- DB row type (matches Nova schema) ---

interface SubmissionRow {
  slug: string;
  display_name: string;
  description: string;
  avatar_url: string;
  brand_name: string;
  subscriber_count: string;
  group: string;
  enabled: number;
  display_order: number;
  theme_json: string;
  link_youtube: string;
  link_twitter: string;
  link_facebook: string;
  link_instagram: string;
  link_twitch: string;
  external_url: string;
}

// --- Registry types (match data/registry.json) ---

interface SocialLinks {
  youtube?: string;
  twitter?: string;
  facebook?: string;
  instagram?: string;
  twitch?: string;
}

interface ThemeColors {
  accentPrimary: string;
  accentPrimaryDark: string;
  accentPrimaryLight: string;
  accentSecondary: string;
  accentSecondaryLight: string;
  bgPageStart: string;
  bgPageMid: string;
  bgPageEnd: string;
  bgAccentPrimary: string;
  bgAccentPrimaryMuted: string;
  borderAccentPrimary: string;
  borderAccentSecondary: string;
}

interface StreamerConfig {
  slug: string;
  displayName: string;
  description: string;
  avatarUrl: string;
  brandName: string;
  subscriberCount: string;
  group: string;
  socialLinks: SocialLinks;
  theme: ThemeColors;
  externalUrl?: string;
  enabled: boolean;
}

// --- Query Nova D1 ---

function queryNovaDb(): SubmissionRow[] {
  const sql = [
    'SELECT slug, display_name, description, avatar_url, brand_name,',
    'subscriber_count, "group", enabled, display_order, theme_json,',
    'link_youtube, link_twitter, link_facebook, link_instagram, link_twitch, external_url',
    "FROM submissions WHERE status = 'approved' AND enabled = 1 ORDER BY display_order, slug",
  ].join(' ');

  const raw = execFileSync(
    'npx',
    ['wrangler', 'd1', 'execute', 'oshi-prism-nova', '--remote', '--json', `--command=${sql}`],
    { cwd: NOVA_DIR, encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 },
  );

  const parsed = JSON.parse(raw);
  // wrangler d1 --json returns an array; the first element has .results
  const results: SubmissionRow[] = parsed[0]?.results ?? [];
  return results;
}

// --- Transform DB row → registry config ---

function buildSocialLinks(row: SubmissionRow): SocialLinks {
  const links: SocialLinks = {};
  if (row.link_youtube) links.youtube = row.link_youtube;
  if (row.link_twitter) links.twitter = row.link_twitter;
  if (row.link_facebook) links.facebook = row.link_facebook;
  if (row.link_instagram) links.instagram = row.link_instagram;
  if (row.link_twitch) links.twitch = row.link_twitch;
  return links;
}

function isAllBlackTheme(theme: ThemeColors): boolean {
  return Object.values(theme).every((v) => v === '#000000');
}

function parseTheme(row: SubmissionRow): ThemeColors {
  if (!row.theme_json) {
    throw new Error(`Streamer "${row.slug}" has empty theme_json — curator must set theme colors before sync.`);
  }
  try {
    return JSON.parse(row.theme_json) as ThemeColors;
  } catch {
    throw new Error(`Streamer "${row.slug}" has invalid theme_json: ${row.theme_json}`);
  }
}

function rowToConfig(row: SubmissionRow): StreamerConfig {
  const config: StreamerConfig = {
    slug: row.slug,
    displayName: row.display_name,
    description: row.description,
    avatarUrl: row.avatar_url,
    brandName: row.brand_name,
    subscriberCount: row.subscriber_count,
    group: row.group,
    socialLinks: buildSocialLinks(row),
    theme: parseTheme(row),
    enabled: true, // only enabled rows are queried
  };
  if (row.external_url) {
    config.externalUrl = row.external_url;
  }
  return config;
}

// --- Write output files ---

function writeRegistry(streamers: StreamerConfig[]): void {
  const registry = { version: 1, streamers };
  const json = JSON.stringify(registry, null, 2) + '\n';
  fs.writeFileSync(REGISTRY_PATH, json, 'utf-8');
  console.log(`  wrote ${REGISTRY_PATH} (${streamers.length} streamers)`);
}

function writeSlugs(streamers: StreamerConfig[]): void {
  const slugs = streamers.map((s) => s.slug);
  const content = [
    '// Auto-generated by tools/sync-registry/sync.ts — do not edit manually.',
    '// Must stay in sync with data/registry.json.',
    `export const ALL_STREAMER_SLUGS: string[] = ${JSON.stringify(slugs)};`,
    '',
  ].join('\n');
  fs.writeFileSync(SLUGS_PATH, content, 'utf-8');
  console.log(`  wrote ${SLUGS_PATH}`);
}

function scaffoldDataDirs(streamers: StreamerConfig[]): void {
  for (const s of streamers) {
    const dir = path.resolve(ROOT, 'data', s.slug);
    if (fs.existsSync(dir)) continue;

    console.log(`  scaffolding data/${s.slug}/`);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'songs.json'), '[]\n', 'utf-8');
    fs.writeFileSync(path.join(dir, 'streams.json'), '[]\n', 'utf-8');
    fs.mkdirSync(path.join(dir, 'metadata'), { recursive: true });
  }
}

// --- Main ---

function main(): void {
  console.log('sync-registry: querying Nova DB for approved submissions...');
  const rows = queryNovaDb();

  if (rows.length === 0) {
    console.error('ERROR: No approved+enabled submissions found in Nova DB.');
    process.exit(1);
  }

  console.log(`  found ${rows.length} approved streamer(s): ${rows.map((r) => r.slug).join(', ')}`);

  const streamers = rows.map(rowToConfig);

  // Fall back to mizuki's theme for streamers with all-#000000 placeholder themes
  const mizuki = streamers.find((s) => s.slug === 'mizuki');
  if (mizuki) {
    for (const s of streamers) {
      if (s.slug !== 'mizuki' && isAllBlackTheme(s.theme)) {
        console.log(`  ⚠ ${s.slug} has placeholder theme (all #000000), using mizuki theme as default`);
        s.theme = { ...mizuki.theme };
      }
    }
  }

  writeRegistry(streamers);
  writeSlugs(streamers);
  scaffoldDataDirs(streamers);

  console.log('sync-registry: done.');
}

main();
