// Auto-generated by tools/sync-registry/sync.ts — do not edit manually.
// Must stay in sync with data/registry.json.
export const ALL_STREAMER_SLUGS: string[] = ["mizuki","gabu","seki","minatoaqua","earendel","galaxyvt","hibiki","hitomi","hiyori","inori","iruni","itsuki","kirali","koe","koyuki","lilylinglan","nemesis","oboro","oumua","paitan","rei","sachi","sakuro","thirteennn013","xxhacucoxx","yuzumi"];
