// Auto-generated by tools/sync-registry/sync.ts — do not edit manually.
// Must stay in sync with data/registry.json.
export const ALL_STREAMER_SLUGS: string[] = ["mizuki","gabu","itsuki","kirali"];
