// Auto-generated by tools/sync-registry/sync.ts — do not edit manually.
// Must stay in sync with data/registry.json.
export const ALL_STREAMER_SLUGS: string[] = ["mizuki","gabu","seki","earendel","galaxyvt","hibiki","hibikuotodama","hitomi","hiyori","inori","iruni","itsuki","kirali","koe","koyuki","lilylinglan","mendy","minatoaqua","nagi","nemesis","oboro","otowamina","oumua","paitan","rei","sachi","sakuro","shumulumeifei","thirteennn013","xxhacucoxx","yuzumi"];
