/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 615df985e84487ef1724c141b2a7f2b9)
interface __BaseEnv_Env {
	VOD_EXPORT_PUBLIC: R2Bucket;
	VOD_EXPORT_PRIVATE: R2Bucket;
	DB: D1Database;
	NOVA_DB: D1Database;
	CRYSTAL_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	CURATOR_EMAILS: "z54981220@gmail.com";
	VOD_EXPORT_DB_ID: "92d81cb5-d307-4fc3-b55c-49b5a29ed729";
	VOD_EXPORT_NOVA_DB_ID: "ebf4d5ff-68f9-4e2e-b95c-9afefd0cbc0c";
	DEV_AUTH_EMAIL: string;
	YOUTUBE_API_KEY: string;
	DISCORD_WEBHOOK_ANNOUNCE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
