/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false --strict-vars=false` (hash: b2fc973b0be3215e40e5f577d2aea79e)
interface __BaseEnv_Env {
	VOD_EXPORT_PUBLIC: R2Bucket;
	VOD_EXPORT_PRIVATE: R2Bucket;
	DB: D1Database;
	NOVA_DB: D1Database;
	CRYSTAL_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	CURATOR_EMAILS: string;
	VOD_EXPORT_DB_ID: string;
	VOD_EXPORT_NOVA_DB_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
