name = "prism-admin"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[build]
command = "cd .. && npm install"

# Serve the admin UI as static assets from the Worker
[assets]
directory = "./ui/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[vars]
# Comma-separated list of curator emails
CURATOR_EMAILS = "z54981220@gmail.com"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "oshi-prism-db"
database_id = "92d81cb5-d307-4fc3-b55c-49b5a29ed729"

[[d1_databases]]
binding = "NOVA_DB"
database_name = "oshi-prism-nova"
database_id = "ebf4d5ff-68f9-4e2e-b95c-9afefd0cbc0c"

[[d1_databases]]
binding = "CRYSTAL_DB"
database_name = "oshi-crystal"
database_id = "2d3e6cc0-a54a-483e-a819-0c552347265b"
